- .github/CODEOWNERS
- stylelint-config-landr/index.js
- stylelint-config-landr/package.json
We need to have leading zeros for numbers because prettier adds this automatically and there is [no way to turn that off in prettier](https://github.com/prettier/prettier/issues/2705).
BONUS: Fixed a typo in the CODEOWNERS file
> fix(stylelint-config-landr): leading zero

- prettier-config-landr/index.js
- prettier-config-landr/package.json
Tab width should be 4 spaces for JSON, SCSS, and HTML files as that is what is currently being used in our web app and Guest Site.
> fix(prettier-config-landr): set tabWidth for json, scss, and html files

- eslint-config-landr/index.js
- eslint-config-landr/package.json
This setting orders imports in a way that places external imports on top and relative imports afterwards. I've prevented the option of having spaces between import statements because I was getting some weird behaviour when permitting spaces between imports.
With this rule, we should no longer be asking people to manually re-order import statements in pull requests.
> feat(eslint-config-landr): add import/order rule

- eslint-config-landr/package.json
- eslint-config-landr/yarn.lock
Forgot to add a required peer dependency of `eslint-import-order`.
> fix(eslint-config-landr): add missing peer dependency

- eslint-config-landr/index.js
- eslint-config-landr/package.json
Forgot to add the `import` plugin to the `plugins` array of the ESLint config file 🤦‍♂️
> fix(eslint-config-landr): add missing plugin to plugins array

- prettier-config-landr/index.js
- prettier-config-landr/package.json
100 characters is really short when using 4 spaces tabWidth.
https://hackernoon.com/does-column-width-of-80-make-sense-in-2018-50c161fbdcf6
before prettier i was using 140 characters but it will be nice to compromise at least to 120.
Let's open the discussion
100 char in blue - vs - vertical line (120)
not done yet
> chore: update printWidth settings in prettier

- README.md
update readme with bump version rules.
It will be nice to set our MAJOR Repos to use landr linting and formating packages like that `1.X` so we do not have to update them all the time. But in order to do that we need to agree in a set of rules, And we will have to manually update the package only in certains situations.
**Open for Feedback**
> chore: update readme with bump version rules

- .github/CODEOWNERS
- .gitignore
- .vscode/settings.json
- eslint-config-landr/index.js
- eslint-config-landr/package.json
- eslint-config-landr/react.js
- package.json
- prettier-config-landr/package.json
- stylelint-config-landr/package.json
- yarn.lock
This PR updates the dependencies of all packages.
Move all Typescript related rules in the overrides for only `ts` and `tsx` files. This allows javascript files to NOT be parse with Typescript
> feat: update dependencies and configs

- eslint-config-landr/package.json
- eslint-config-landr/react.js
Pr will disable react/display-name rule.
It prohibits defining inline components with arrow functions and requires definition with named function instead.
Example from here (https://github.com/yannickcr/eslint-plugin-react/issues/597):
```
//warn
const wrapWithToastProvider = Comp => props => (
<ToastProvider>
<Comp {...props} />
</ToastProvider>
);
// no warn
function wrapWithToastProvider(Comp) {
return function WrappedWithToast(props) {
return (
<ToastProvider>
<Comp {...props} />
</ToastProvider>
);
};
}
```
> feat(react-display-name): disable rule

- eslint-config-landr/package.json
- package.json
- prettier-config-landr/package.json
Bump dependencies to fix Peer dependencies issues in other repos.
We are now using Prettier 2.x 
https://mixgenius.atlassian.net/browse/CHFE-578
> Fix: fix peer dependencies and use prettier 2.X

- package.json
Remove jira from opensource repo
<details>
<br />
```bash
npm install eslint-config-landr@0.4.1-canary.58.a5469cc.0
npm install prettier-config-landr@0.1.2-canary.58.a5469cc.0
npm install stylelint-config-landr@0.0.7-canary.58.a5469cc.0
yarn add eslint-config-landr@0.4.1-canary.58.a5469cc.0
yarn add prettier-config-landr@0.1.2-canary.58.a5469cc.0
yarn add stylelint-config-landr@0.0.7-canary.58.a5469cc.0
```
</details>
> fix: remove jira from opensource repo

- .gitignore
- package.json
- yarn.lock
This PR adds husky and lint-staged
<details>
<br />
```bash
npm install eslint-config-landr@0.4.1-canary.63.5d67468.0
npm install prettier-config-landr@0.1.2-canary.63.5d67468.0
npm install stylelint-config-landr@0.0.7-canary.63.5d67468.0
yarn add eslint-config-landr@0.4.1-canary.63.5d67468.0
yarn add prettier-config-landr@0.1.2-canary.63.5d67468.0
yarn add stylelint-config-landr@0.0.7-canary.63.5d67468.0
```
</details>
> fix: add husky and lint-staged

- packages/eslint-config-landr/index.js
- yarn.lock
There’s a rule in our eslint config called no-use-before-define which forces us to declare functions before executing them.
In JavaScript, functions are hoisted by the interpreter automatically before being executed and that’s always been the case.
That means that something like this is super legit
```tsx
toto()
function toto(){
console.log("hi")
}
```
This is the same kind of behaviours you can expect when calling methods in classes.
Declarations are interpreted first, initializations after.
But our rule stops us from using this language feature and often gets in the way when splitting complex functions into smaller functions by complaining about a useless ordering issue.
I feel it also obfuscates files because the file thing you see in a file are sub functions used by the main export …
> feat: disable no use before define

- packages/eslint-config-landr/package.json
- yarn.lock
Bump dependencies for eslint because the version of typescript we use on the projects repo was no longer supported.
<details>
<br />
```bash
npm install eslint-config-landr@1.0.1-canary.96.4893d98.0
yarn add eslint-config-landr@1.0.1-canary.96.4893d98.0
```
</details>
> chore: bump dependencies

- packages/eslint-config-landr/index.js
When using typescript import paths, we need to keep the same order as without the paths.
Ex.
**Before**
```typescript
import external from '@external/plugin';
import { MyHook } from '../../../../hooks/myHook';
import { MyComponent } from './MyComponent';
```
**After**
```typescript
import external from '@external/plugin';
import { MyHook } from '@/hooks/myHook';
import { MyComponent } from './MyComponent';
```
Without changing the rule, the `@/` import was placed after the `./MyComponent`, which makes it a bit harder to read and find your sub components.
With the rule change, it keeps them in the same order.
> feat(lint): add pattern for typescript paths to eslint import order

- packages/eslint-config-landr/lingui.js
- packages/eslint-config-landr/package.json
- yarn.lock
Move lingui to `dependecies`
<details>
<br />
```bash
npm install eslint-config-landr@1.3.1-canary.114.61031ac.0
yarn add eslint-config-landr@1.3.1-canary.114.61031ac.0
```
</details>
> fix(lingui): move lingui to dependecies

- .github/workflows/release.yml
- package.json
- packages/eslint-config-landr/index.js
- packages/eslint-config-landr/package.json
- packages/prettier-config-landr/package.json
- yarn.lock
Update dependencies versions. Stay on eslint 8 since v9 has a lot of breaking changes (complete rewrite..)
<details>
<br />
```bash
npm install eslint-config-landr@1.5.0-canary.120.89f4b85.0
npm install prettier-config-landr@1.1.0-canary.120.89f4b85.0
yarn add eslint-config-landr@1.5.0-canary.120.89f4b85.0
yarn add prettier-config-landr@1.1.0-canary.120.89f4b85.0
```
</details>
> BREAKING CHANGE: update dependencies

- packages/eslint-config-landr/package.json
- packages/eslint-config-landr/translate.js
- yarn.lock
Adds an es lint plugin that helps identify cases where we are conditionally rendering text nodes next to other siblings. This is a known issue that can cause React to crash.
You can read more about the rules in the yarn package description
https://classic.yarnpkg.com/en/package/eslint-plugin-react-google-translate
Examples of code that will throw an error:
<details>
<br />
```bash
npm install eslint-config-landr@1.5.0-canary.123.b43c1c5.0
yarn add eslint-config-landr@1.5.0-canary.123.b43c1c5.0
```
</details>
> feat: Add React Google Translate Plugin for ES Lint

- packages/prettier-config-landr/index.js
For modules files we could have `.cjs` and `.mjs` files to use a proper `module.exports` or `export default`
Update prettier config to support those files and
have the same indentation
> fix(prettier): support cjs and mts files

- packages/eslint-config-landr/package.json
Got an issue with master build that had wrong package.json version for eslint-config-landr
This aims to fix the build on master
<details>
<br />
```bash
npm install eslint-config-landr@1.5.1-canary.127.0fe2c54.0
npm install prettier-config-landr@1.0.2-canary.127.0fe2c54.0
yarn add eslint-config-landr@1.5.1-canary.127.0fe2c54.0
yarn add prettier-config-landr@1.0.2-canary.127.0fe2c54.0
```
</details>
> fix(build): manually bump eslint-config-landr
