LandrAudio/linting-and-formatting

eslint-config-landr/README.md
eslint-config-landr/package.json

Added instructions regarding the installation of peer dependencies. I've also added an `engines` field to the `package.json` ([copied from Airbnb](https://github.com/airbnb/javascript/blob/60b96d322277c4c71a21a05caba8eb3320e0e3fa/packages/eslint-config-airbnb/package.json#L81-L83)).

Add note regarding peer dependencies

---

eslint-config-landr/README.md
eslint-config-landr/package.json

- Add README instruction to install `eslint` as a dev dependency
- Fix incorrect email
- Add repository URL so the NPM package page can link to the Github page

Add minor fixes for eslint-config-landr

---

eslint-config-landr/package.json

Forgot to do this in the last PR.

Update eslint-config-landr package number

---

prettier-config-landr/index.js
prettier-config-landr/package.json

The tab width should be 4 for JS & TS files.

Add tabWidth value of 4 for JS & TS files.

---

eslint-config-landr/index.js
eslint-config-landr/package.json

Add no-undef override for tsx files

---

README.md

Add description of existing packages

---

.github/CODEOWNERS

Add Ben as a codeowner because he is potentially a nice guy

---

README.md

Added note regarding editor configuration.

docs(linting-and-formatting): add note regarding editor configuration

---

.github/CODEOWNERS

Henry, you have been nominated as a code owner for this prestigious repository.

chore: add Henry as a code owner

---

prettier-config-landr/index.js
prettier-config-landr/package.json

feat(prettier-config-landr): give mdx files tabWidth 4

---

eslint-config-landr/index.js
eslint-config-landr/package.json

Adds a rule that prefers the use of object destructuring.

feat(eslint-config-prettier): add prefer-destructuring rule

---

eslint-config-landr/index.js
eslint-config-landr/package.json

Added some config options that allow to parse JSX and ES6 syntax.

feat(eslint-config-landr): add options to support React

---

eslint-config-landr/README.md
eslint-config-landr/index.js
eslint-config-landr/package.json
eslint-config-landr/react.js
yarn.lock

This PR add a specific eslint config for React.

feat(eslint): add react plugin

---

eslint-config-landr/index.js
eslint-config-landr/package.json

PR will add no-return-await rule.
Here is some info about this rule https://eslint.org/docs/rules/no-return-await

feat(eslint): add no-return-await rule

---

eslint-config-landr/index.js
eslint-config-landr/package.json
eslint-config-landr/react.js
yarn.lock

We need all those rules for Projects and Library MFEs.
https://eslint.org/docs/rules/array-callback-return
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-unused-vars.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-react.md
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md

fix(eslint): extend rules

---

.github/CODEOWNERS

- ~[ ] Updated the version number in the `package.json`~
- ~[ ] Test any new configuration on a repo using [`npm link`](https://docs.npmjs.com/cli/link)~

Add @hjack-landr to codeowners

---

README.md
package.json
packages/eslint-config-landr/package.json
packages/prettier-config-landr/package.json
packages/stylelint-config-landr/package.json

This PR updates the `author` field in the package.json of each project

chore: update author in package.json

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

This PR updates the README and removes the checklist item about bumping version in packages in the PR template

doc: update readme and PR template

---

package.json
yarn.lock

This PR adds the Slack plugin for Auto to post release note to a channel.
For now this will post to a temporary channel. This will be changed to `#chapter-frontend` in a future PR.

fix: update auto and add slack plugin

---

.github/workflows/release.yml
packages/eslint-config-landr/package.json
packages/prettier-config-landr/package.json
packages/stylelint-config-landr/package.json
yarn.lock

Fix authentication in Github Action and bump `package.json` to latest version.
<details>
<br />
```bash
npm install eslint-config-landr@0.8.1-canary.91.65078bd.0
npm install prettier-config-landr@0.3.1-canary.91.65078bd.0
npm install stylelint-config-landr@0.3.1-canary.91.65078bd.0
yarn add eslint-config-landr@0.8.1-canary.91.65078bd.0
yarn add prettier-config-landr@0.3.1-canary.91.65078bd.0
yarn add stylelint-config-landr@0.3.1-canary.91.65078bd.0
```
</details>

build: use token for checkout

---

package.json

Update auto dependencies label to increase the version to patch on dependencies update

feat(auto): update auto dependencies label

---

.github/workflows/release.yml
packages/eslint-config-landr/package.json
packages/prettier-config-landr/package.json

Add admin token to be able to push on master
Manually bump versions as previous ones
were published to NPM
<details>
<br />
```bash
npm install eslint-config-landr@1.6.1-canary.128.539b7ea.0
npm install prettier-config-landr@1.1.1-canary.128.539b7ea.0
yarn add eslint-config-landr@1.6.1-canary.128.539b7ea.0
yarn add prettier-config-landr@1.1.1-canary.128.539b7ea.0
```
</details>

fix: build issues on master

---

.github/workflows/release.yml
packages/eslint-config-landr/package.json
packages/prettier-config-landr/package.json

Try again and clone with admin token
<details>
<br />
```bash
npm install eslint-config-landr@1.7.1-canary.129.efff9ef.0
npm install prettier-config-landr@1.2.1-canary.129.efff9ef.0
yarn add eslint-config-landr@1.7.1-canary.129.efff9ef.0
yarn add prettier-config-landr@1.2.1-canary.129.efff9ef.0
```
</details>

fix: build master issue - take 3
